import { getDb } from '../src/client';
import { users, sources, palettes, colors, tags, paletteTags, likes } from '../src/schema';
import dotenv from 'dotenv';
import { eq } from 'drizzle-orm';

// Load environment variables
dotenv.config({ path: '.env.local' });

/**
 * Bot user data - 20 generated usernames for auto-likes
 */
const BOT_USERS = [
  { displayName: 'ColorCrafter', email: 'colorcrafter@kulrs.bot' },
  { displayName: 'PalettePixie', email: 'palettepixie@kulrs.bot' },
  { displayName: 'HueMaster', email: 'huemaster@kulrs.bot' },
  { displayName: 'ChromaQueen', email: 'chromaqueen@kulrs.bot' },
  { displayName: 'TintTitan', email: 'tinttitan@kulrs.bot' },
  { displayName: 'ShadeSeeker', email: 'shadeseeker@kulrs.bot' },
  { displayName: 'SpectrumSage', email: 'spectrumsage@kulrs.bot' },
  { displayName: 'VibrantViper', email: 'vibrantviper@kulrs.bot' },
  { displayName: 'PastelPanda', email: 'pastelpanda@kulrs.bot' },
  { displayName: 'NeonNinja', email: 'neonninja@kulrs.bot' },
  { displayName: 'GradientGuru', email: 'gradientguru@kulrs.bot' },
  { displayName: 'SwatchStar', email: 'swatchstar@kulrs.bot' },
  { displayName: 'PigmentPro', email: 'pigmentpro@kulrs.bot' },
  { displayName: 'ToneTamer', email: 'tonetamer@kulrs.bot' },
  { displayName: 'ColorCurator', email: 'colorcurator@kulrs.bot' },
  { displayName: 'ArtisticAura', email: 'artisticaura@kulrs.bot' },
  { displayName: 'RainbowRider', email: 'rainbowrider@kulrs.bot' },
  { displayName: 'DesignDragon', email: 'designdragon@kulrs.bot' },
  { displayName: 'StyleSorcerer', email: 'stylesorcerer@kulrs.bot' },
  { displayName: 'ColorCompass', email: 'colorcompass@kulrs.bot' },
];

/**
 * Seed script for development demo data
 * This script is idempotent - it can be safely re-run without duplicating data
 */

async function seed() {
  console.log('🌱 Seeding database with demo data...');
  
  const db = getDb();
  
  try {
    // 1. Create demo sources
    console.log('  → Creating sources...');
    const sourceData = [
      { name: 'user-created', description: 'Palette created by user' },
      { name: 'imported', description: 'Palette imported from external source' },
      { name: 'ai-generated', description: 'Palette generated by AI' },
    ];
    
    for (const src of sourceData) {
      const existing = await db.select().from(sources).where(eq(sources.name, src.name)).limit(1);
      if (existing.length === 0) {
        await db.insert(sources).values(src);
        console.log(`    ✓ Created source: ${src.name}`);
      } else {
        console.log(`    ⊙ Source already exists: ${src.name}`);
      }
    }
    
    // 2. Create demo user
    console.log('  → Creating demo user...');
    const demoFirebaseUid = 'demo-user-12345';
    let demoUser = await db.select().from(users).where(eq(users.firebaseUid, demoFirebaseUid)).limit(1);
    
    if (demoUser.length === 0) {
      demoUser = await db.insert(users).values({
        firebaseUid: demoFirebaseUid,
        email: 'demo@kulrs.com',
        displayName: 'Demo User',
      }).returning();
      console.log('    ✓ Created demo user');
    } else {
      console.log('    ⊙ Demo user already exists');
    }
    
    const userId = demoUser[0].id;
    
    // 3. Create bot users for auto-likes
    console.log('  → Creating bot users...');
    const botUserIds: string[] = [];
    
    for (const bot of BOT_USERS) {
      const firebaseUid = `bot-${bot.displayName.toLowerCase()}`;
      const existing = await db.select().from(users).where(eq(users.firebaseUid, firebaseUid)).limit(1);
      
      if (existing.length === 0) {
        const [newBot] = await db.insert(users).values({
          firebaseUid,
          email: bot.email,
          displayName: bot.displayName,
          isBot: true,
        }).returning();
        botUserIds.push(newBot.id);
        console.log(`    ✓ Created bot user: ${bot.displayName}`);
      } else {
        botUserIds.push(existing[0].id);
        console.log(`    ⊙ Bot user already exists: ${bot.displayName}`);
      }
    }
    
    // Get source IDs
    const allSources = await db.select().from(sources);
    const userCreatedSource = allSources.find(s => s.name === 'user-created');
    
    // 3. Create demo tags
    console.log('  → Creating tags...');
    const tagData = [
      { name: 'Nature', slug: 'nature', description: 'Natural color palettes' },
      { name: 'Vibrant', slug: 'vibrant', description: 'Bold and vibrant colors' },
      { name: 'Pastel', slug: 'pastel', description: 'Soft pastel colors' },
      { name: 'Monochrome', slug: 'monochrome', description: 'Single color variations' },
      { name: 'Warm', slug: 'warm', description: 'Warm color schemes' },
      { name: 'Cool', slug: 'cool', description: 'Cool color schemes' },
      { name: 'Serene', slug: 'serene', description: 'Calm and peaceful palettes' },
      { name: 'Energetic', slug: 'energetic', description: 'Dynamic and lively palettes' },
      { name: 'Romantic', slug: 'romantic', description: 'Soft and romantic color schemes' },
      { name: 'Dark', slug: 'dark', description: 'Deep and dark palettes' },
      { name: 'Earthy', slug: 'earthy', description: 'Natural earth tones' },
      { name: 'Neon', slug: 'neon', description: 'Bright neon colors' },
      { name: 'Vintage', slug: 'vintage', description: 'Retro and vintage aesthetics' },
      { name: 'Tropical', slug: 'tropical', description: 'Bright tropical themes' },
      { name: 'Floral', slug: 'floral', description: 'Soft floral-inspired palettes' },
      { name: 'Nordic', slug: 'nordic', description: 'Muted Scandinavian palettes' },
    ];
    
    const createdTags = [];
    for (const tag of tagData) {
      const existing = await db.select().from(tags).where(eq(tags.slug, tag.slug)).limit(1);
      if (existing.length === 0) {
        const [newTag] = await db.insert(tags).values(tag).returning();
        createdTags.push(newTag);
        console.log(`    ✓ Created tag: ${tag.name}`);
      } else {
        createdTags.push(existing[0]);
        console.log(`    ⊙ Tag already exists: ${tag.name}`);
      }
    }
    
    // 4. Create demo palettes
    console.log('  → Creating demo palettes...');
    const paletteData = [
      {
        name: 'Ocean Breeze',
        description: 'Calming ocean-inspired colors',
        colors: ['#0077BE', '#00A8E8', '#00C9FF', '#7DD3FC', '#BAE6FD'],
        tagSlugs: ['cool', 'nature', 'serene'],
      },
      {
        name: 'Sunset Glow',
        description: 'Warm sunset gradient',
        colors: ['#FF6B6B', '#FF8E53', '#FFB347', '#FFD93D', '#FFF176'],
        tagSlugs: ['warm', 'vibrant', 'energetic'],
      },
      {
        name: 'Forest Canopy',
        description: 'Deep forest greens',
        colors: ['#1B4332', '#2D6A4F', '#40916C', '#52B788', '#74C69D'],
        tagSlugs: ['nature', 'cool', 'earthy'],
      },
      {
        name: 'Lavender Dream',
        description: 'Soft lavender pastels',
        colors: ['#E8D5E8', '#D4B5D4', '#C096C0', '#AC76AC', '#985698'],
        tagSlugs: ['pastel', 'cool', 'romantic'],
      },
      {
        name: 'Autumn Palette',
        description: 'Rich autumn colors',
        colors: ['#8B4513', '#A0522D', '#CD853F', '#DAA520', '#F4A460'],
        tagSlugs: ['warm', 'nature', 'earthy'],
      },
      {
        name: 'Midnight Depths',
        description: 'Dark mysterious blues and purples',
        colors: ['#1A1A2E', '#16213E', '#0F3460', '#533483', '#E94560'],
        tagSlugs: ['dark', 'cool'],
      },
      {
        name: 'Desert Sands',
        description: 'Warm earthy tones from arid landscapes',
        colors: ['#C2803D', '#D4A46A', '#E8C99A', '#F5E6CA', '#8B4513'],
        tagSlugs: ['warm', 'earthy', 'nature'],
      },
      {
        name: 'Tropical Burst',
        description: 'Vivid tropical paradise colors',
        colors: ['#FF6B35', '#F7C59F', '#EFEFD0', '#004E89', '#1A936F'],
        tagSlugs: ['tropical', 'vibrant', 'energetic'],
      },
      {
        name: 'Rose Garden',
        description: 'Delicate floral pinks and greens',
        colors: ['#FF6B8A', '#FF8FAB', '#FFB3C6', '#B5E48C', '#52B788'],
        tagSlugs: ['romantic', 'floral', 'pastel'],
      },
      {
        name: 'Nordic Frost',
        description: 'Muted Scandinavian inspired tones',
        colors: ['#2E4057', '#048A81', '#54C6EB', '#EEF5DB', '#8EE3EF'],
        tagSlugs: ['nordic', 'cool', 'serene'],
      },
      {
        name: 'Neon City',
        description: 'Electric neon lights of the urban night',
        colors: ['#FF1493', '#00FFFF', '#ADFF2F', '#FF4500', '#BF5FFF'],
        tagSlugs: ['neon', 'vibrant', 'energetic'],
      },
      {
        name: 'Antique Collection',
        description: 'Faded vintage warmth',
        colors: ['#C17817', '#8B4513', '#5C4033', '#F4E1C1', '#D2B48C'],
        tagSlugs: ['vintage', 'warm', 'earthy'],
      },
      {
        name: 'Spring Meadow',
        description: 'Fresh greens and soft florals',
        colors: ['#A8D5BA', '#FDE68A', '#FCA5A5', '#C4B5FD', '#6EE7B7'],
        tagSlugs: ['floral', 'nature', 'pastel'],
      },
      {
        name: 'Cherry Blossom',
        description: 'Delicate Japanese spring palette',
        colors: ['#FADADD', '#F4A7B9', '#E8869A', '#C94F6C', '#A3274A'],
        tagSlugs: ['romantic', 'floral', 'pastel'],
      },
      {
        name: 'Grayscale Classic',
        description: 'Timeless monochrome spectrum',
        colors: ['#1A1A1A', '#404040', '#808080', '#BFBFBF', '#F2F2F2'],
        tagSlugs: ['monochrome', 'dark'],
      },
    ];
    
    for (const paletteInfo of paletteData) {
      const existingPalette = await db.select().from(palettes)
        .where(eq(palettes.name, paletteInfo.name))
        .limit(1);
      
      if (existingPalette.length === 0) {
        // Create palette
        const [newPalette] = await db.insert(palettes).values({
          name: paletteInfo.name,
          description: paletteInfo.description,
          userId,
          sourceId: userCreatedSource?.id,
          isPublic: true,
        }).returning();
        
        // Add colors
        for (let i = 0; i < paletteInfo.colors.length; i++) {
          await db.insert(colors).values({
            paletteId: newPalette.id,
            hexValue: paletteInfo.colors[i],
            position: i,
          });
        }
        
        // Add tags
        for (const tagSlug of paletteInfo.tagSlugs) {
          const tag = createdTags.find(t => t.slug === tagSlug);
          if (tag) {
            await db.insert(paletteTags).values({
              paletteId: newPalette.id,
              tagId: tag.id,
            });
          }
        }
        
        // Add random likes from bot users (3-12 likes per palette)
        const numLikes = Math.floor(Math.random() * 10) + 3;
        const shuffledBots = [...botUserIds].sort(() => Math.random() - 0.5);
        const likeCount = Math.min(numLikes, shuffledBots.length);
        
        for (let i = 0; i < likeCount; i++) {
          await db.insert(likes).values({
            paletteId: newPalette.id,
            userId: shuffledBots[i],
          });
        }
        
        // Update the likes count on the palette
        await db.update(palettes)
          .set({ likesCount: likeCount })
          .where(eq(palettes.id, newPalette.id));
        
        console.log(`    ✓ Created palette: ${paletteInfo.name} (${paletteInfo.colors.length} colors, ${likeCount} likes)`);
      } else {
        console.log(`    ⊙ Palette already exists: ${paletteInfo.name}`);
      }
    }
    
    console.log('✅ Database seeded successfully!');
    console.log('\n📊 Summary:');
    console.log(`   - ${sourceData.length} sources`);
    console.log(`   - 1 demo user`);
    console.log(`   - ${BOT_USERS.length} bot users`);
    console.log(`   - ${tagData.length} tags`);
    console.log(`   - ${paletteData.length} palettes (with random likes)`);
    
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    throw error;
  } finally {
    process.exit(0);
  }
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
