import { getDb } from '../src/client';
import { users, sources, palettes, colors, tags, paletteTags } from '../src/schema';
import dotenv from 'dotenv';
import { eq } from 'drizzle-orm';

// Load environment variables
dotenv.config({ path: '.env.local' });

/**
 * Seed script for development demo data
 * This script is idempotent - it can be safely re-run without duplicating data
 */

async function seed() {
  console.log('🌱 Seeding database with demo data...');
  
  const db = getDb();
  
  try {
    // 1. Create demo sources
    console.log('  → Creating sources...');
    const sourceData = [
      { name: 'user-created', description: 'Palette created by user' },
      { name: 'imported', description: 'Palette imported from external source' },
      { name: 'ai-generated', description: 'Palette generated by AI' },
    ];
    
    for (const src of sourceData) {
      const existing = await db.select().from(sources).where(eq(sources.name, src.name)).limit(1);
      if (existing.length === 0) {
        await db.insert(sources).values(src);
        console.log(`    ✓ Created source: ${src.name}`);
      } else {
        console.log(`    ⊙ Source already exists: ${src.name}`);
      }
    }
    
    // 2. Create demo user
    console.log('  → Creating demo user...');
    const demoFirebaseUid = 'demo-user-12345';
    let demoUser = await db.select().from(users).where(eq(users.firebaseUid, demoFirebaseUid)).limit(1);
    
    if (demoUser.length === 0) {
      demoUser = await db.insert(users).values({
        firebaseUid: demoFirebaseUid,
        email: 'demo@kulrs.com',
        displayName: 'Demo User',
      }).returning();
      console.log('    ✓ Created demo user');
    } else {
      console.log('    ⊙ Demo user already exists');
    }
    
    const userId = demoUser[0].id;
    
    // Get source IDs
    const allSources = await db.select().from(sources);
    const userCreatedSource = allSources.find(s => s.name === 'user-created');
    
    // 3. Create demo tags
    console.log('  → Creating tags...');
    const tagData = [
      { name: 'Nature', slug: 'nature', description: 'Natural color palettes' },
      { name: 'Vibrant', slug: 'vibrant', description: 'Bold and vibrant colors' },
      { name: 'Pastel', slug: 'pastel', description: 'Soft pastel colors' },
      { name: 'Monochrome', slug: 'monochrome', description: 'Single color variations' },
      { name: 'Warm', slug: 'warm', description: 'Warm color schemes' },
      { name: 'Cool', slug: 'cool', description: 'Cool color schemes' },
    ];
    
    const createdTags = [];
    for (const tag of tagData) {
      const existing = await db.select().from(tags).where(eq(tags.slug, tag.slug)).limit(1);
      if (existing.length === 0) {
        const [newTag] = await db.insert(tags).values(tag).returning();
        createdTags.push(newTag);
        console.log(`    ✓ Created tag: ${tag.name}`);
      } else {
        createdTags.push(existing[0]);
        console.log(`    ⊙ Tag already exists: ${tag.name}`);
      }
    }
    
    // 4. Create demo palettes
    console.log('  → Creating demo palettes...');
    const paletteData = [
      {
        name: 'Ocean Breeze',
        description: 'Calming ocean-inspired colors',
        colors: ['#0077BE', '#00A8E8', '#00C9FF', '#7DD3FC', '#BAE6FD'],
        tagSlugs: ['cool', 'nature'],
      },
      {
        name: 'Sunset Glow',
        description: 'Warm sunset gradient',
        colors: ['#FF6B6B', '#FF8E53', '#FFB347', '#FFD93D', '#FFF176'],
        tagSlugs: ['warm', 'vibrant'],
      },
      {
        name: 'Forest Canopy',
        description: 'Deep forest greens',
        colors: ['#1B4332', '#2D6A4F', '#40916C', '#52B788', '#74C69D'],
        tagSlugs: ['nature', 'cool'],
      },
      {
        name: 'Lavender Dream',
        description: 'Soft lavender pastels',
        colors: ['#E8D5E8', '#D4B5D4', '#C096C0', '#AC76AC', '#985698'],
        tagSlugs: ['pastel', 'cool'],
      },
      {
        name: 'Autumn Palette',
        description: 'Rich autumn colors',
        colors: ['#8B4513', '#A0522D', '#CD853F', '#DAA520', '#F4A460'],
        tagSlugs: ['warm', 'nature'],
      },
    ];
    
    for (const paletteInfo of paletteData) {
      const existingPalette = await db.select().from(palettes)
        .where(eq(palettes.name, paletteInfo.name))
        .limit(1);
      
      if (existingPalette.length === 0) {
        // Create palette
        const [newPalette] = await db.insert(palettes).values({
          name: paletteInfo.name,
          description: paletteInfo.description,
          userId,
          sourceId: userCreatedSource?.id,
          isPublic: true,
        }).returning();
        
        // Add colors
        for (let i = 0; i < paletteInfo.colors.length; i++) {
          await db.insert(colors).values({
            paletteId: newPalette.id,
            hexValue: paletteInfo.colors[i],
            position: i,
          });
        }
        
        // Add tags
        for (const tagSlug of paletteInfo.tagSlugs) {
          const tag = createdTags.find(t => t.slug === tagSlug);
          if (tag) {
            await db.insert(paletteTags).values({
              paletteId: newPalette.id,
              tagId: tag.id,
            });
          }
        }
        
        console.log(`    ✓ Created palette: ${paletteInfo.name} (${paletteInfo.colors.length} colors)`);
      } else {
        console.log(`    ⊙ Palette already exists: ${paletteInfo.name}`);
      }
    }
    
    console.log('✅ Database seeded successfully!');
    console.log('\n📊 Summary:');
    console.log(`   - ${sourceData.length} sources`);
    console.log(`   - 1 demo user`);
    console.log(`   - ${tagData.length} tags`);
    console.log(`   - ${paletteData.length} palettes`);
    
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    throw error;
  } finally {
    process.exit(0);
  }
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
