export {
  NOTE_NAMES,
  type NoteName,
  type ChordQuality,
  type MusicNote,
  type ChordStep,
  type ColorMusicMapping,
  type Composition,
  hueToSemitone,
  lightnessToOctave,
  chromaToQuality,
  lightnessToVelocity,
  colorToChord,
  hexToOklchApprox,
  paletteToComposition,
  midiToFrequency,
  buildChordStep,
} from './mappings.js';

export {
  type ScaleType,
  type KeySignature,
  type ChordInKey,
  type ProgressionPreset,
  type ChordSuggestion,
  PROGRESSION_PRESETS,
  getChordsInKey,
  progressionToChords,
  progressionToComposition,
  detectKey,
  suggestAlternatives,
  paletteToHarmonicComposition,
  chordToHex,
} from './theory.js';
