export {
  NOTE_NAMES,
  type NoteName,
  type ChordQuality,
  type MusicNote,
  type ChordStep,
  type ColorMusicMapping,
  type Composition,
  hueToSemitone,
  lightnessToOctave,
  chromaToQuality,
  lightnessToVelocity,
  colorToChord,
  hexToOklchApprox,
  paletteToComposition,
  midiToFrequency,
  buildChordStep,
} from './mappings.js';
